/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasirkita;

import java.awt.Color;
import java.awt.HeadlessException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.io.File;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author hanif
 */
public class KasirKita extends javax.swing.JFrame {

    /**
     * Creates new form KasirKita
     */
    DefaultTableModel TabelKasir;
    String[] data;
    NumberFormat formatKurensi;
    File simpanan;
    File file;
    BufferedWriter bw;
    BufferedReader br;
    Date waktu;
    SimpleDateFormat formatTanggal;
    JFrame input;

    public KasirKita() {
        initComponents();
        data = new String[4];
        simpanan = new File("src/Data");
        waktu = new Date();
        formatTanggal = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
        formatKurensi = NumberFormat.getCurrencyInstance(getLocale());
        TabelKasir = (DefaultTableModel) jTable1.getModel();
        input = new JFrame("Masukkan Qty");
        TFHarga.setEditable(false);
        TFNamaBarang.setEditable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Load = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        LabelNamaBarang = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        TFHarga = new javax.swing.JTextField();
        TFNamaBarang = new javax.swing.JTextField();
        TotalBelanja = new javax.swing.JLabel();
        HasilTB = new javax.swing.JLabel();
        Zeus = new javax.swing.JLabel();
        Techies = new javax.swing.JLabel();
        PA = new javax.swing.JLabel();
        MK = new javax.swing.JLabel();
        CM = new javax.swing.JLabel();
        TB = new javax.swing.JLabel();
        Lina = new javax.swing.JLabel();
        Pudge = new javax.swing.JLabel();
        SF = new javax.swing.JLabel();
        LC = new javax.swing.JLabel();
        Jugger = new javax.swing.JLabel();
        IO = new javax.swing.JLabel();
        Rubick = new javax.swing.JLabel();
        EXit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 760));
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(1300, 760));
        getContentPane().setLayout(null);

        jTable1.setBackground(jLabel1.getBackground());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Barang", "Harga Barang", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(900, 200, 370, 340);

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });
        getContentPane().add(Load);
        Load.setBounds(1090, 560, 70, 60);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(1200, 560, 70, 60);

        LabelNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNamaBarang.setForeground(new java.awt.Color(255, 0, 51));
        LabelNamaBarang.setText("Nama Barang");
        getContentPane().add(LabelNamaBarang);
        LabelNamaBarang.setBounds(900, 90, 80, 30);

        LabelHarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelHarga.setForeground(new java.awt.Color(255, 0, 51));
        LabelHarga.setText("Harga Barang");
        getContentPane().add(LabelHarga);
        LabelHarga.setBounds(900, 140, 80, 30);
        getContentPane().add(TFHarga);
        TFHarga.setBounds(1000, 140, 270, 30);
        getContentPane().add(TFNamaBarang);
        TFNamaBarang.setBounds(1000, 90, 270, 30);

        TotalBelanja.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalBelanja.setForeground(new java.awt.Color(255, 0, 51));
        TotalBelanja.setText("TOTAL BELANJA :");
        getContentPane().add(TotalBelanja);
        TotalBelanja.setBounds(740, 650, 220, 60);

        HasilTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HasilTB.setForeground(new java.awt.Color(255, 0, 51));
        HasilTB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(HasilTB);
        HasilTB.setBounds(980, 650, 290, 60);

        Zeus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zeus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Tempest_Helm_of_the_Thundergod.png"))); // NOI18N
        Zeus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZeusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ZeusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ZeusMouseExited(evt);
            }
        });
        getContentPane().add(Zeus);
        Zeus.setBounds(20, 80, 210, 140);

        Techies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Techies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Swine_of_the_Sunken_Galley.png"))); // NOI18N
        Techies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TechiesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TechiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TechiesMouseExited(evt);
            }
        });
        getContentPane().add(Techies);
        Techies.setBounds(240, 80, 210, 140);

        PA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Manifold_Paradox.png"))); // NOI18N
        PA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PAMouseExited(evt);
            }
        });
        getContentPane().add(PA);
        PA.setBounds(460, 80, 210, 140);

        MK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Great_Sage's_Reckoning.png"))); // NOI18N
        MK.setMaximumSize(new java.awt.Dimension(200, 133));
        MK.setMinimumSize(new java.awt.Dimension(200, 133));
        MK.setPreferredSize(new java.awt.Dimension(200, 133));
        MK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MKMouseExited(evt);
            }
        });
        getContentPane().add(MK);
        MK.setBounds(680, 80, 210, 140);

        CM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Frost_Avalanche.png"))); // NOI18N
        CM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CMMouseExited(evt);
            }
        });
        getContentPane().add(CM);
        CM.setBounds(20, 240, 210, 140);

        TB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Fractal_Horns_of_Inner_Abysm.png"))); // NOI18N
        TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TBMouseExited(evt);
            }
        });
        getContentPane().add(TB);
        TB.setBounds(240, 240, 210, 140);

        Lina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Fiery_Soul_of_the_Slayer.png"))); // NOI18N
        Lina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LinaMouseExited(evt);
            }
        });
        getContentPane().add(Lina);
        Lina.setBounds(460, 240, 210, 140);

        Pudge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pudge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Feast_of_Abscession.png"))); // NOI18N
        Pudge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PudgeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PudgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PudgeMouseExited(evt);
            }
        });
        getContentPane().add(Pudge);
        Pudge.setBounds(680, 240, 210, 140);

        SF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Demon_Eater.png"))); // NOI18N
        SF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SFMouseExited(evt);
            }
        });
        getContentPane().add(SF);
        SF.setBounds(20, 400, 210, 140);

        LC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Blades_of_Voth_Domosh.png"))); // NOI18N
        LC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LCMouseExited(evt);
            }
        });
        getContentPane().add(LC);
        LC.setBounds(240, 400, 210, 140);

        Jugger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jugger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Bladeform_Legacy.png"))); // NOI18N
        Jugger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JuggerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JuggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JuggerMouseExited(evt);
            }
        });
        getContentPane().add(Jugger);
        Jugger.setBounds(460, 400, 210, 140);

        IO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Benevolent_Companion.png"))); // NOI18N
        IO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IOMouseExited(evt);
            }
        });
        getContentPane().add(IO);
        IO.setBounds(680, 400, 210, 140);

        Rubick.setBackground(jLabel1.getBackground());
        Rubick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rubick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_The_Magus_Cypher.png"))); // NOI18N
        Rubick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RubickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RubickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RubickMouseExited(evt);
            }
        });
        getContentPane().add(Rubick);
        Rubick.setBounds(350, 570, 210, 140);

        EXit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EXit.setForeground(new java.awt.Color(255, 0, 51));
        EXit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EXit.setText("X");
        EXit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EXitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EXitMouseExited(evt);
            }
        });
        getContentPane().add(EXit);
        EXit.setBounds(1270, 0, 34, 20);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("TOKO KITA PILIH ARCANAMU :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 880, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper2you_458870.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loaddata(){
        file = new File("src/Data/DataArcana.txt");
        try {
            br = new BufferedReader(new FileReader(file));
            
            String barisPertama = br.readLine();
            //pisah teks pada barisPertama dengan tanda koma(,)
            //kemudian masukkan ke array
            String[] namaKolom = barisPertama.split("#");            
        } catch (IOException e) {
        }
    }
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        TabelKasir.removeRow(jTable1.getSelectedRow());
        for (int i = jTable1.getSelectedRowCount(); i < TabelKasir.getRowCount(); i++) {
            TabelKasir.setValueAt(i + 1, i, 0);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        file = new File("src/Data/wkwk");
        try {
            Object[] dataBaris = br.lines().toArray();
            String barisPertama = br.readLine();

            String[] namaKolom = barisPertama.split(",");
            //ambil model dan atur nama kolom tabel
            TabelKasir.setColumnIdentifiers(namaKolom);
            //ambil baris selanjutnya secara keseluruhan
            //dan masukkan ke array
            for (int i = 0; i < dataBaris.length; i++) {
                //ambil tiap baris dari dataBaris
                String baris = dataBaris[i].toString();
                //pisah baris dengan tanda / dan masukkan array
                String[] datatxt = baris.split("/");
                //data masukan ke tabel
                TabelKasir.addRow(datatxt);
            }
            br.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_LoadActionPerformed

    private void ZeusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseEntered
        Zeus.setOpaque(true);
        Zeus.setBackground(Color.RED);
        TFNamaBarang.setText("Tempest Helm of the Thundergod");
        TFHarga.setText(formatKurensi.format(800000));
    }//GEN-LAST:event_ZeusMouseEntered

    private void ZeusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseExited
        Zeus.setBackground(getBackground());
        Zeus.setOpaque(false);
        TFNamaBarang.setText("");
        TFHarga.setText("");
    }//GEN-LAST:event_ZeusMouseExited

    private void TechiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseEntered
        Techies.setOpaque(true);
        Techies.setBackground(Color.RED);
        TFNamaBarang.setText("Swine of the Sunken Galley");
        TFHarga.setText(formatKurensi.format(750000));
    }//GEN-LAST:event_TechiesMouseEntered

    private void TechiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseExited
        Techies.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        Techies.setOpaque(false);
    }//GEN-LAST:event_TechiesMouseExited

    private void PAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseEntered
        PA.setOpaque(true);
        PA.setBackground(Color.RED);
        TFNamaBarang.setText("Manifold Paradox");
        TFHarga.setText(formatKurensi.format(700000));
    }//GEN-LAST:event_PAMouseEntered

    private void PAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseExited
        PA.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        PA.setOpaque(false);
    }//GEN-LAST:event_PAMouseExited

    private void MKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseEntered
        MK.setOpaque(true);
        MK.setBackground(Color.RED);
        TFNamaBarang.setText("Great Sage's Reckoning");
        TFHarga.setText(formatKurensi.format(650000));
    }//GEN-LAST:event_MKMouseEntered

    private void MKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseExited
        MK.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        MK.setOpaque(false);
    }//GEN-LAST:event_MKMouseExited

    private void CMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseEntered
        CM.setOpaque(true);
        CM.setBackground(Color.RED);
        TFNamaBarang.setText("Frost Avalanche");
        TFHarga.setText(formatKurensi.format(600000));
    }//GEN-LAST:event_CMMouseEntered

    private void CMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseExited
        TFNamaBarang.setText("");
        CM.setBackground(getBackground());
        TFHarga.setText("");
        CM.setOpaque(false);
    }//GEN-LAST:event_CMMouseExited

    private void TBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseEntered
        TB.setOpaque(true);
        TB.setBackground(Color.RED);
        TFNamaBarang.setText("Fractal Horns of Inner Abysm");
        TFHarga.setText(formatKurensi.format(550000));
    }//GEN-LAST:event_TBMouseEntered

    private void TBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseExited
        TB.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        TB.setOpaque(false);
    }//GEN-LAST:event_TBMouseExited

    private void LinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseEntered
        Lina.setOpaque(true);
        Lina.setBackground(Color.RED);
        TFNamaBarang.setText("Fiery Soul of the Slayer");
        TFHarga.setText(formatKurensi.format(500000));
    }//GEN-LAST:event_LinaMouseEntered

    private void LinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseExited
        Lina.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        Lina.setOpaque(false);
    }//GEN-LAST:event_LinaMouseExited

    private void PudgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseEntered
        Pudge.setOpaque(true);
        Pudge.setBackground(Color.RED);
        TFNamaBarang.setText("Feast of Abscession");
        TFHarga.setText(formatKurensi.format(450000));
    }//GEN-LAST:event_PudgeMouseEntered

    private void PudgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseExited
        Pudge.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        Pudge.setOpaque(false);
    }//GEN-LAST:event_PudgeMouseExited

    private void SFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseEntered
        SF.setOpaque(true);
        SF.setBackground(Color.RED);
        TFNamaBarang.setText("Demon Eater");
        TFHarga.setText(formatKurensi.format(400000));
    }//GEN-LAST:event_SFMouseEntered

    private void SFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseExited
        SF.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        SF.setOpaque(false);
    }//GEN-LAST:event_SFMouseExited

    private void LCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseEntered
        LC.setOpaque(true);
        LC.setBackground(Color.RED);
        TFNamaBarang.setText("Blades of Voth Domosh");
        TFHarga.setText(formatKurensi.format(350000));
    }//GEN-LAST:event_LCMouseEntered

    private void LCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseExited
        LC.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        LC.setOpaque(false);
    }//GEN-LAST:event_LCMouseExited

    private void JuggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseEntered
        Jugger.setOpaque(true);
        Jugger.setBackground(Color.RED);
        TFNamaBarang.setText("Bladeform Legacy");
        TFHarga.setText(formatKurensi.format(300000));
    }//GEN-LAST:event_JuggerMouseEntered

    private void JuggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseExited
        Jugger.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        Jugger.setOpaque(false);
    }//GEN-LAST:event_JuggerMouseExited

    private void IOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseEntered
        IO.setOpaque(true);
        IO.setBackground(Color.RED);
        TFNamaBarang.setText("Benevolent Companion");
        TFHarga.setText(formatKurensi.format(250000));
    }//GEN-LAST:event_IOMouseEntered

    private void IOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseExited
        IO.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        IO.setOpaque(false);
    }//GEN-LAST:event_IOMouseExited

    private void RubickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseEntered
        Rubick.setOpaque(true);
        Rubick.setBackground(Color.RED);
        TFNamaBarang.setText("The Magus Cypher");
        TFHarga.setText(formatKurensi.format(200000));
    }//GEN-LAST:event_RubickMouseEntered

    private void RubickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseExited
        Rubick.setBackground(getBackground());
        TFNamaBarang.setText("");
        TFHarga.setText("");
        Rubick.setOpaque(false);
    }//GEN-LAST:event_RubickMouseExited

    private void ZeusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseClicked
        Belikuy();
    }//GEN-LAST:event_ZeusMouseClicked

    private void TechiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseClicked
        Belikuy();
    }//GEN-LAST:event_TechiesMouseClicked

    private void PAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseClicked
        Belikuy();
    }//GEN-LAST:event_PAMouseClicked

    private void MKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseClicked
        Belikuy();
    }//GEN-LAST:event_MKMouseClicked

    private void CMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseClicked
        Belikuy();
    }//GEN-LAST:event_CMMouseClicked

    private void TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseClicked
        Belikuy();
    }//GEN-LAST:event_TBMouseClicked

    private void LinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseClicked
        Belikuy();
    }//GEN-LAST:event_LinaMouseClicked

    private void PudgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseClicked
        Belikuy();
    }//GEN-LAST:event_PudgeMouseClicked

    private void SFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseClicked
        Belikuy();
    }//GEN-LAST:event_SFMouseClicked

    private void LCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseClicked
        Belikuy();
    }//GEN-LAST:event_LCMouseClicked

    private void JuggerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseClicked
        Belikuy();
    }//GEN-LAST:event_JuggerMouseClicked

    private void IOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseClicked
        Belikuy();
    }//GEN-LAST:event_IOMouseClicked

    private void RubickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseClicked
        Belikuy();
    }//GEN-LAST:event_RubickMouseClicked

    private void EXitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_EXitMouseClicked

    private void EXitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseEntered
        EXit.setOpaque(true);
        EXit.setBackground(Color.BLUE);
    }//GEN-LAST:event_EXitMouseEntered

    private void EXitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseExited
        EXit.setBackground(getBackground());
        EXit.setOpaque(false);
    }//GEN-LAST:event_EXitMouseExited

    private void Belikuy() throws HeadlessException {
        String qty = JOptionPane.showInputDialog(input, "Berapa yang akan anda beli?");
        if (TFNamaBarang.getText().trim().isEmpty() || TFHarga.getText().trim().isEmpty() || qty.isEmpty()) {

        } else {
            data[0] = Integer.toString(TabelKasir.getRowCount() + 1);
            data[1] = TFNamaBarang.getText();
            data[2] = TFHarga.getText();
            data[3] = qty;
            boolean belumAda = true;
            for (int i = 0; i < TabelKasir.getRowCount(); i++) {
                if (data[1].equals(TabelKasir.getValueAt(i, 1))) {
                    belumAda = false;
                    break;
                }
            }
            if (belumAda) {
                TabelKasir.addRow(data);
                TFNamaBarang.setText("");
                TFHarga.setText("");
                Double total = 0.0;
                for (int i = 0; i < TabelKasir.getRowCount(); i++) {
                    String harga = (String) TabelKasir.getValueAt(i, 2);
                    Double temp = Double.parseDouble((String) TabelKasir.getValueAt(i, 3)) * Double.parseDouble(harga.replaceAll("[^0-9.]", ""));
                    total += temp;
                }
                HasilTB.setText(formatKurensi.format(total));               
            } else {
                JOptionPane.showMessageDialog(null, "Data sudah ada !!!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirKita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CM;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel EXit;
    private javax.swing.JLabel HasilTB;
    private javax.swing.JLabel IO;
    private javax.swing.JLabel Jugger;
    private javax.swing.JLabel LC;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelNamaBarang;
    private javax.swing.JLabel Lina;
    private javax.swing.JButton Load;
    private javax.swing.JLabel MK;
    private javax.swing.JLabel PA;
    private javax.swing.JLabel Pudge;
    private javax.swing.JLabel Rubick;
    private javax.swing.JLabel SF;
    private javax.swing.JLabel TB;
    private javax.swing.JTextField TFHarga;
    private javax.swing.JTextField TFNamaBarang;
    private javax.swing.JLabel Techies;
    private javax.swing.JLabel TotalBelanja;
    private javax.swing.JLabel Zeus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
