/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasirkita;

import java.awt.Color;
import java.awt.HeadlessException;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.io.File;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author hanif
 */
public class KasirKita extends javax.swing.JFrame {

    /**
     * Creates new form KasirKita
     */
    DefaultTableModel TabelKasir;
    String[] data;
    String[] stock;
    NumberFormat formatKurensi;
    File simpanan;
    File file;
    BufferedWriter bw;
    BufferedReader br;
    Date waktu;
    SimpleDateFormat formatTanggal;
    JFrame input;

    public KasirKita() {
        initComponents();
        data = new String[4];
        simpanan = new File("src/Data");
        waktu = new Date();
        formatKurensi = NumberFormat.getCurrencyInstance(getLocale());
        TabelKasir = (DefaultTableModel) jTable1.getModel();
        input = new JFrame("Masukkan Qty");
        setLocationRelativeTo(this);
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelNamaBarang1 = new javax.swing.JLabel();
        LabelNamaBarang = new javax.swing.JLabel();
        StockAvailable1 = new javax.swing.JLabel();
        StockAvailable = new javax.swing.JLabel();
        LabelHarga1 = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        BAYAR = new javax.swing.JLabel();
        TotalBelanja1 = new javax.swing.JLabel();
        TotalBelanja = new javax.swing.JLabel();
        KEMBALIANTB = new javax.swing.JLabel();
        BAYARTB = new javax.swing.JLabel();
        HasilTB = new javax.swing.JLabel();
        Zeus = new javax.swing.JLabel();
        Techies = new javax.swing.JLabel();
        PA = new javax.swing.JLabel();
        MK = new javax.swing.JLabel();
        CM = new javax.swing.JLabel();
        TB = new javax.swing.JLabel();
        Lina = new javax.swing.JLabel();
        Pudge = new javax.swing.JLabel();
        SF = new javax.swing.JLabel();
        LC = new javax.swing.JLabel();
        Jugger = new javax.swing.JLabel();
        IO = new javax.swing.JLabel();
        Rubick = new javax.swing.JLabel();
        EXit = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        PROCEED = new javax.swing.JLabel();
        History = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/b37ee2f20af88890f3cc51fcb8f2898dfa95e777_full.jpg")).getImage());
        setMaximumSize(new java.awt.Dimension(1300, 760));
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(1300, 760));
        getContentPane().setLayout(null);

        jTable1.setBackground(Background.getBackground());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Barang", "Harga Barang", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(900, 200, 370, 230);

        LabelNamaBarang1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNamaBarang1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(LabelNamaBarang1);
        LabelNamaBarang1.setBounds(1030, 40, 240, 40);

        LabelNamaBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNamaBarang.setForeground(new java.awt.Color(255, 0, 51));
        LabelNamaBarang.setText("Nama Item :");
        getContentPane().add(LabelNamaBarang);
        LabelNamaBarang.setBounds(900, 40, 90, 40);

        StockAvailable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StockAvailable1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(StockAvailable1);
        StockAvailable1.setBounds(1030, 140, 240, 40);

        StockAvailable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StockAvailable.setForeground(new java.awt.Color(255, 0, 51));
        StockAvailable.setText("Stock Available :");
        getContentPane().add(StockAvailable);
        StockAvailable.setBounds(900, 140, 130, 40);

        LabelHarga1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelHarga1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(LabelHarga1);
        LabelHarga1.setBounds(1030, 90, 240, 40);

        LabelHarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelHarga.setForeground(new java.awt.Color(255, 0, 51));
        LabelHarga.setText("Harga @Item :");
        getContentPane().add(LabelHarga);
        LabelHarga.setBounds(900, 90, 110, 40);

        BAYAR.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BAYAR.setForeground(new java.awt.Color(255, 0, 51));
        BAYAR.setText("BAYAR :");
        getContentPane().add(BAYAR);
        BAYAR.setBounds(670, 620, 220, 60);

        TotalBelanja1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalBelanja1.setForeground(new java.awt.Color(255, 0, 51));
        TotalBelanja1.setText("KEMBALIAN :");
        getContentPane().add(TotalBelanja1);
        TotalBelanja1.setBounds(670, 690, 220, 60);

        TotalBelanja.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalBelanja.setForeground(new java.awt.Color(255, 0, 51));
        TotalBelanja.setText("TOTAL BELANJA :");
        getContentPane().add(TotalBelanja);
        TotalBelanja.setBounds(670, 550, 220, 60);

        KEMBALIANTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        KEMBALIANTB.setForeground(new java.awt.Color(255, 0, 51));
        KEMBALIANTB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(KEMBALIANTB);
        KEMBALIANTB.setBounds(930, 690, 340, 60);

        BAYARTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BAYARTB.setForeground(new java.awt.Color(255, 0, 51));
        BAYARTB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(BAYARTB);
        BAYARTB.setBounds(930, 620, 340, 60);

        HasilTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HasilTB.setForeground(new java.awt.Color(255, 0, 51));
        HasilTB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(HasilTB);
        HasilTB.setBounds(930, 550, 340, 60);

        Zeus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zeus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Tempest_Helm_of_the_Thundergod.png"))); // NOI18N
        Zeus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZeusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ZeusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ZeusMouseExited(evt);
            }
        });
        getContentPane().add(Zeus);
        Zeus.setBounds(20, 80, 210, 140);

        Techies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Techies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Swine_of_the_Sunken_Galley.png"))); // NOI18N
        Techies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TechiesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TechiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TechiesMouseExited(evt);
            }
        });
        getContentPane().add(Techies);
        Techies.setBounds(240, 80, 210, 140);

        PA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Manifold_Paradox.png"))); // NOI18N
        PA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PAMouseExited(evt);
            }
        });
        getContentPane().add(PA);
        PA.setBounds(460, 80, 210, 140);

        MK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Great_Sage's_Reckoning.png"))); // NOI18N
        MK.setMaximumSize(new java.awt.Dimension(200, 133));
        MK.setMinimumSize(new java.awt.Dimension(200, 133));
        MK.setPreferredSize(new java.awt.Dimension(200, 133));
        MK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MKMouseExited(evt);
            }
        });
        getContentPane().add(MK);
        MK.setBounds(680, 80, 210, 140);

        CM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Frost_Avalanche.png"))); // NOI18N
        CM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CMMouseExited(evt);
            }
        });
        getContentPane().add(CM);
        CM.setBounds(20, 240, 210, 140);

        TB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Fractal_Horns_of_Inner_Abysm.png"))); // NOI18N
        TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TBMouseExited(evt);
            }
        });
        getContentPane().add(TB);
        TB.setBounds(240, 240, 210, 140);

        Lina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Fiery_Soul_of_the_Slayer.png"))); // NOI18N
        Lina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LinaMouseExited(evt);
            }
        });
        getContentPane().add(Lina);
        Lina.setBounds(460, 240, 210, 140);

        Pudge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pudge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Feast_of_Abscession.png"))); // NOI18N
        Pudge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PudgeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PudgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PudgeMouseExited(evt);
            }
        });
        getContentPane().add(Pudge);
        Pudge.setBounds(680, 240, 210, 140);

        SF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Demon_Eater.png"))); // NOI18N
        SF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SFMouseExited(evt);
            }
        });
        getContentPane().add(SF);
        SF.setBounds(20, 400, 210, 140);

        LC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Blades_of_Voth_Domosh.png"))); // NOI18N
        LC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LCMouseExited(evt);
            }
        });
        getContentPane().add(LC);
        LC.setBounds(240, 400, 210, 140);

        Jugger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jugger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Bladeform_Legacy.png"))); // NOI18N
        Jugger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JuggerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JuggerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JuggerMouseExited(evt);
            }
        });
        getContentPane().add(Jugger);
        Jugger.setBounds(460, 400, 210, 140);

        IO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_Benevolent_Companion.png"))); // NOI18N
        IO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IOMouseExited(evt);
            }
        });
        getContentPane().add(IO);
        IO.setBounds(680, 400, 210, 140);

        Rubick.setBackground(Background.getBackground());
        Rubick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rubick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200px-Cosmetic_icon_The_Magus_Cypher.png"))); // NOI18N
        Rubick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RubickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RubickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RubickMouseExited(evt);
            }
        });
        getContentPane().add(Rubick);
        Rubick.setBounds(350, 570, 210, 140);

        EXit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EXit.setForeground(new java.awt.Color(255, 0, 51));
        EXit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EXit.setText("X");
        EXit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EXitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EXitMouseExited(evt);
            }
        });
        getContentPane().add(EXit);
        EXit.setBounds(1260, 0, 34, 20);

        Judul.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 0, 51));
        Judul.setText("DOTA2COMMUNITYSTORE");
        getContentPane().add(Judul);
        Judul.setBounds(10, 10, 880, 60);

        PROCEED.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PROCEED.setForeground(new java.awt.Color(255, 0, 51));
        PROCEED.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PROCEED.setText("PROCEED");
        PROCEED.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        PROCEED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROCEEDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROCEEDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROCEEDMouseExited(evt);
            }
        });
        getContentPane().add(PROCEED);
        PROCEED.setBounds(1150, 470, 120, 60);

        History.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        History.setForeground(new java.awt.Color(255, 0, 51));
        History.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        History.setText("Reset");
        History.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistoryMouseExited(evt);
            }
        });
        getContentPane().add(History);
        History.setBounds(1020, 470, 100, 60);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b37ee2f20af88890f3cc51fcb8f2898dfa95e777_full - Copy.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 570, 190, 184);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper2you_458870.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1300, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loaddata() {
        file = new File("src/Data/DataArcana.txt");
        try {
            br = new BufferedReader(new FileReader(file));

            String barisPertama = br.readLine();
            //pisah teks pada barisPertama dengan tanda koma(,)
            //kemudian masukkan ke array         
            stock = barisPertama.split("#");
        } catch (IOException e) {
        }
    }
    private void ZeusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseEntered
        Zeus.setOpaque(true);
        Zeus.setBackground(Color.RED);
        LabelNamaBarang1.setText("Tempest Helm of the Thundergod");
        LabelHarga1.setText(formatKurensi.format(800000));
        StockAvailable1.setText(stock[0]);
    }//GEN-LAST:event_ZeusMouseEntered

    private void ZeusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseExited
        Zeus.setBackground(getBackground());
        Zeus.setOpaque(false);
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
    }//GEN-LAST:event_ZeusMouseExited

    private void TechiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseEntered
        Techies.setOpaque(true);
        Techies.setBackground(Color.RED);
        LabelNamaBarang1.setText("Swine of the Sunken Galley");
        LabelHarga1.setText(formatKurensi.format(750000));
        StockAvailable1.setText(stock[1]);
    }//GEN-LAST:event_TechiesMouseEntered

    private void TechiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseExited
        Techies.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        Techies.setOpaque(false);
    }//GEN-LAST:event_TechiesMouseExited

    private void PAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseEntered
        PA.setOpaque(true);
        PA.setBackground(Color.RED);
        LabelNamaBarang1.setText("Manifold Paradox");
        LabelHarga1.setText(formatKurensi.format(700000));
        StockAvailable1.setText(stock[2]);
    }//GEN-LAST:event_PAMouseEntered

    private void PAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseExited
        PA.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        PA.setOpaque(false);
    }//GEN-LAST:event_PAMouseExited

    private void MKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseEntered
        MK.setOpaque(true);
        MK.setBackground(Color.RED);
        LabelNamaBarang1.setText("Great Sage's Reckoning");
        LabelHarga1.setText(formatKurensi.format(650000));
        StockAvailable1.setText(stock[3]);
    }//GEN-LAST:event_MKMouseEntered

    private void MKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseExited
        MK.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        MK.setOpaque(false);
    }//GEN-LAST:event_MKMouseExited

    private void CMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseEntered
        CM.setOpaque(true);
        CM.setBackground(Color.RED);
        LabelNamaBarang1.setText("Frost Avalanche");
        LabelHarga1.setText(formatKurensi.format(600000));
        StockAvailable1.setText(stock[4]);
    }//GEN-LAST:event_CMMouseEntered

    private void CMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseExited
        LabelNamaBarang1.setText("");
        CM.setBackground(getBackground());
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        CM.setOpaque(false);
    }//GEN-LAST:event_CMMouseExited

    private void TBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseEntered
        TB.setOpaque(true);
        TB.setBackground(Color.RED);
        LabelNamaBarang1.setText("Fractal Horns of Inner Abysm");
        LabelHarga1.setText(formatKurensi.format(550000));
        StockAvailable1.setText(stock[5]);
    }//GEN-LAST:event_TBMouseEntered

    private void TBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseExited
        TB.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        TB.setOpaque(false);
    }//GEN-LAST:event_TBMouseExited

    private void LinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseEntered
        Lina.setOpaque(true);
        Lina.setBackground(Color.RED);
        LabelNamaBarang1.setText("Fiery Soul of the Slayer");
        LabelHarga1.setText(formatKurensi.format(500000));
        StockAvailable1.setText(stock[6]);
    }//GEN-LAST:event_LinaMouseEntered

    private void LinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseExited
        Lina.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        Lina.setOpaque(false);
    }//GEN-LAST:event_LinaMouseExited

    private void PudgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseEntered
        Pudge.setOpaque(true);
        Pudge.setBackground(Color.RED);
        LabelNamaBarang1.setText("Feast of Abscession");
        LabelHarga1.setText(formatKurensi.format(450000));
        StockAvailable1.setText(stock[7]);
    }//GEN-LAST:event_PudgeMouseEntered

    private void PudgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseExited
        Pudge.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        Pudge.setOpaque(false);
    }//GEN-LAST:event_PudgeMouseExited

    private void SFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseEntered
        SF.setOpaque(true);
        SF.setBackground(Color.RED);
        LabelNamaBarang1.setText("Demon Eater");
        LabelHarga1.setText(formatKurensi.format(400000));
        StockAvailable1.setText(stock[8]);
    }//GEN-LAST:event_SFMouseEntered

    private void SFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseExited
        SF.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        SF.setOpaque(false);
    }//GEN-LAST:event_SFMouseExited

    private void LCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseEntered
        LC.setOpaque(true);
        LC.setBackground(Color.RED);
        LabelNamaBarang1.setText("Blades of Voth Domosh");
        LabelHarga1.setText(formatKurensi.format(350000));
        StockAvailable1.setText(stock[9]);
    }//GEN-LAST:event_LCMouseEntered

    private void LCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseExited
        LC.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        LC.setOpaque(false);
    }//GEN-LAST:event_LCMouseExited

    private void JuggerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseEntered
        Jugger.setOpaque(true);
        Jugger.setBackground(Color.RED);
        LabelNamaBarang1.setText("Bladeform Legacy");
        LabelHarga1.setText(formatKurensi.format(300000));
        StockAvailable1.setText(stock[10]);
    }//GEN-LAST:event_JuggerMouseEntered

    private void JuggerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseExited
        Jugger.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        Jugger.setOpaque(false);
    }//GEN-LAST:event_JuggerMouseExited

    private void IOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseEntered
        IO.setOpaque(true);
        IO.setBackground(Color.RED);
        LabelNamaBarang1.setText("Benevolent Companion");
        LabelHarga1.setText(formatKurensi.format(250000));
        StockAvailable1.setText(stock[11]);
    }//GEN-LAST:event_IOMouseEntered

    private void IOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseExited
        IO.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        IO.setOpaque(false);
    }//GEN-LAST:event_IOMouseExited

    private void RubickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseEntered
        Rubick.setOpaque(true);
        Rubick.setBackground(Color.RED);
        LabelNamaBarang1.setText("The Magus Cypher");
        LabelHarga1.setText(formatKurensi.format(200000));
        StockAvailable1.setText(stock[12]);
    }//GEN-LAST:event_RubickMouseEntered

    private void RubickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseExited
        Rubick.setBackground(getBackground());
        LabelNamaBarang1.setText("");
        LabelHarga1.setText("");
        StockAvailable1.setText("");
        Rubick.setOpaque(false);
    }//GEN-LAST:event_RubickMouseExited

    private void ZeusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeusMouseClicked
        Belikuy(0);
    }//GEN-LAST:event_ZeusMouseClicked

    private void TechiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TechiesMouseClicked
        Belikuy(1);
    }//GEN-LAST:event_TechiesMouseClicked

    private void PAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAMouseClicked
        Belikuy(2);
    }//GEN-LAST:event_PAMouseClicked

    private void MKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKMouseClicked
        Belikuy(3);
    }//GEN-LAST:event_MKMouseClicked

    private void CMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseClicked
        Belikuy(4);
    }//GEN-LAST:event_CMMouseClicked

    private void TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseClicked
        Belikuy(5);
    }//GEN-LAST:event_TBMouseClicked

    private void LinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinaMouseClicked
        Belikuy(6);
    }//GEN-LAST:event_LinaMouseClicked

    private void PudgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PudgeMouseClicked
        Belikuy(7);
    }//GEN-LAST:event_PudgeMouseClicked

    private void SFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SFMouseClicked
        Belikuy(8);
    }//GEN-LAST:event_SFMouseClicked

    private void LCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCMouseClicked
        Belikuy(9);
    }//GEN-LAST:event_LCMouseClicked

    private void JuggerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuggerMouseClicked
        Belikuy(10);
    }//GEN-LAST:event_JuggerMouseClicked

    private void IOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IOMouseClicked
        Belikuy(11);
    }//GEN-LAST:event_IOMouseClicked

    private void RubickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubickMouseClicked
        Belikuy(12);
    }//GEN-LAST:event_RubickMouseClicked

    private void EXitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseClicked
        if (HasilTB.getText() == "") {
            System.exit(0);
        }
    }//GEN-LAST:event_EXitMouseClicked

    private void EXitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseEntered
        EXit.setOpaque(true);
        EXit.setBackground(Color.WHITE);
    }//GEN-LAST:event_EXitMouseEntered

    private void EXitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXitMouseExited
        EXit.setBackground(getBackground());
        EXit.setOpaque(false);
    }//GEN-LAST:event_EXitMouseExited

    private void HistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseClicked
        if (BAYARTB.getText() != "") {
            TabelKasir.setRowCount(0);
            HasilTB.setText("");
            BAYARTB.setText("");
            KEMBALIANTB.setText("");
        }
    }//GEN-LAST:event_HistoryMouseClicked

    private void PROCEEDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCEEDMouseEntered
        PROCEED.setOpaque(true);
        PROCEED.setBackground(Color.WHITE);
    }//GEN-LAST:event_PROCEEDMouseEntered

    private void PROCEEDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCEEDMouseExited
        PROCEED.setBackground(getBackground());
        PROCEED.setOpaque(false);
    }//GEN-LAST:event_PROCEEDMouseExited

    private void HistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseEntered
        History.setOpaque(true);
        History.setBackground(Color.WHITE);
    }//GEN-LAST:event_HistoryMouseEntered

    private void HistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseExited
        History.setBackground(getBackground());
        History.setOpaque(false);
    }//GEN-LAST:event_HistoryMouseExited

    private void PROCEEDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCEEDMouseClicked
        String Bbyer = JOptionPane.showInputDialog(input, "Masukkan Bayar");
        String tb = HasilTB.getText();
        Double temp = Double.parseDouble(tb.replaceAll("[^0-9.]", ""));
        Double bbyer = Double.valueOf(Bbyer);
        if (bbyer >= temp) {
            Double kembalian = bbyer - temp;
            BAYARTB.setText(formatKurensi.format(bbyer));
            KEMBALIANTB.setText(formatKurensi.format(kembalian));
        }
    }//GEN-LAST:event_PROCEEDMouseClicked

    private void Belikuy(int Stock) throws HeadlessException {
        file = new File("src/Data/DataArcana.txt");
        String qty = JOptionPane.showInputDialog(input, "Berapa yang akan anda beli?");
        if (LabelNamaBarang1.getText().trim().isEmpty() || LabelHarga1.getText().trim().isEmpty() || qty.isEmpty()) {

        } else {
            data[0] = Integer.toString(TabelKasir.getRowCount() + 1);
            data[1] = LabelNamaBarang1.getText();
            data[2] = LabelHarga1.getText();
            data[3] = qty;
            boolean belumAda = true;
            for (int i = 0; i < TabelKasir.getRowCount(); i++) {
                if (data[1].equals(TabelKasir.getValueAt(i, 1))) {
                    belumAda = false;
                    break;
                }
            }
            if (belumAda && Integer.parseInt(stock[Stock]) >= Integer.parseInt(qty)) {
                TabelKasir.addRow(data);
                LabelNamaBarang1.setText("");
                LabelHarga1.setText("");
                StockAvailable1.setText("");
                Double total = 0.0;
                for (int i = 0; i < TabelKasir.getRowCount(); i++) {
                    String harga = (String) TabelKasir.getValueAt(i, 2);
                    Double temp = Double.parseDouble((String) TabelKasir.getValueAt(i, 3)) * Double.parseDouble(harga.replaceAll("[^0-9.]", ""));
                    total += temp;
                }
                stock[Stock] = String.valueOf(Integer.parseInt(stock[Stock]) - Integer.parseInt(qty));
                HasilTB.setText(formatKurensi.format(total));
                try {
                    bw = new BufferedWriter(new FileWriter(file));
                    for (int i = 0; i < stock.length; i++) {
                        if (i > 0) {
                            bw.write("#");
                        }
                        bw.write(stock[i]);
                    }
                    bw.close();
                } catch (Exception e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "Inputan Error");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirKita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirKita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAYAR;
    private javax.swing.JLabel BAYARTB;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CM;
    private javax.swing.JLabel EXit;
    private javax.swing.JLabel HasilTB;
    private javax.swing.JLabel History;
    private javax.swing.JLabel IO;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Jugger;
    private javax.swing.JLabel KEMBALIANTB;
    private javax.swing.JLabel LC;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelHarga1;
    private javax.swing.JLabel LabelNamaBarang;
    private javax.swing.JLabel LabelNamaBarang1;
    private javax.swing.JLabel Lina;
    private javax.swing.JLabel MK;
    private javax.swing.JLabel PA;
    private javax.swing.JLabel PROCEED;
    private javax.swing.JLabel Pudge;
    private javax.swing.JLabel Rubick;
    private javax.swing.JLabel SF;
    private javax.swing.JLabel StockAvailable;
    private javax.swing.JLabel StockAvailable1;
    private javax.swing.JLabel TB;
    private javax.swing.JLabel Techies;
    private javax.swing.JLabel TotalBelanja;
    private javax.swing.JLabel TotalBelanja1;
    private javax.swing.JLabel Zeus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
